### ISSUE TITLE
Create web interface

### ISSUE THREAD

**Issue by Allanflo88** [Allanflo88/SistemaVendas#2]
Create web Interface using primefaces and the professor "ProjetoMavenJSFPrimeFacesComJPA" aula 03 and 04 interfaces as sample

**Comment by cslclaman** [comment]
**Status:**
- [X] Cadastro Produto
- [X] Cadastro Cliente
- [X] Cadastro Vendedor
- [x] Realizar Pedido

**Comment by Allanflo88** [comment]
Não é "Cadastro pedido" é "Realizar pedido"

**Comment by cslclaman** [comment]
Ok, fixed.
