### ISSUE TITLE
Requeriment change: Isn't better to have an button to "Cancel Order"?

### ISSUE THREAD

**Issue by cslclaman** [Allanflo88/SistemaVendas#22]
In Clients, Sellers and Products pages, we have four buttons: Save, Update, Remove and Cancel.
But it's strange to update an order, or remove them after your placing.

I think that, in the Place order page, it's better to have just two buttons: Save and Cancel Order. The Cancel will act as a Remove button, but with another name. Update will not exist anymore.

**Comment by Allanflo88** [comment]
the button update order is needed because the order may have no payment date.

**Comment by cslclaman** [comment]
Implemented in Consult Order page.
