### ISSUE TITLE
Option to find and select Client and Seller by CPF in Place Order page

### ISSUE THREAD

**Issue by cslclaman** [Allanflo88/SistemaVendas#23]
Like the GUI Realizar Pedido in [cslclaman/pooPrj1](https://github.com/cslclaman/pooPrj1/) , but maintaning the option to select them in ComboBox

**Comment by Allanflo88** [comment]
We don't need this, we need?

**Comment by cslclaman** [comment]
...Well, it's a enhancement, but not really necessary. Maybe an extra point?

**Comment by cslclaman** [comment]
Ok, forget this.
