### ISSUE TITLE
Suggestion: Remove pages menu from sidebar and put it on the top of page

### ISSUE THREAD

**Issue by cslclaman** [Allanflo88/SistemaVendas#7]
Side menu bar is a thing that i see only on Siga. Most sites (including GitHub) have a page menu below header, or doesn't have a header at all.

We can try to change this.

**Comment by Allanflo88** [comment]
It's not dificult to implement, but it's something not important to do, anyway, I agree the page menu below header is more beautiful and grant a better experience.

**Comment by cslclaman** [comment]
Ok, no complains.
